version: "3"
services:
  nusight:
    image: node:lts
    volumes:
      - .:/var/www/NUsight2
      - node_modules_volume:/var/www/NUsight2/node_modules
    working_dir: /var/www/NUsight2
networks:
  default:
    external:
      name: nuclearnet
volumes:
  node_modules_volume:
    driver: local
