steps:
  - label: Build code
    command:
      - yarn
      - yarn build:ci
    plugins:
      - ./.buildkite/plugins/cache: ~
      - docker#v3.5.0:
          image: "node:12"
          always-pull: true
          propagate-uid-gid: true
          environment:
            - "HOME=/workdir"

  - label: Build storybook
    command:
      - yarn
      - yarn storybook:build
    plugins:
      - ./.buildkite/plugins/cache: ~
      - docker#v3.5.0:
          image: "node:12"
          always-pull: true
          propagate-uid-gid: true
          environment:
            - "HOME=/workdir"

  - label: Check code with eslint
    command:
      - yarn
      - yarn eslint
    plugins:
      - ./.buildkite/plugins/cache: ~
      - docker#v3.5.0:
          image: "node:12"
          always-pull: true
          propagate-uid-gid: true
          environment:
            - "HOME=/workdir"

  - label: Test code
    command:
      - yarn
      - yarn test:ci
    plugins:
      - ./.buildkite/plugins/cache: ~
      - docker#v3.5.0:
          image: "node:12"
          always-pull: true
          propagate-uid-gid: true
          environment:
            - "HOME=/workdir"
