#!/bin/bash
set -euo pipefail

echo "--- Storing :yarn: cache"

# Calculate the path to where we store the cache
cache_path=${BUILDKITE_BUILD_PATH}/cache/${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}/$(sha1sum ${BUILDKITE_BUILD_CHECKOUT_PATH}/yarn.lock | cut -f 1 -d' ')

# If we have a cache, load it
mkdir -p ${cache_path}
rsync -a ${BUILDKITE_BUILD_CHECKOUT_PATH}/.cache ${BUILDKITE_BUILD_CHECKOUT_PATH}/node_modules ${cache_path}
